name: pn-ou5
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - astropy
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - black
  - pip
  - cmasher
  - flit
  - jupyter_client<=6.1.12
  - jupyter
  - pip:
      - reproject
