[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mes_longslit"
authors = [{name = "William Henney", email = "whenney@gmail.com"}]
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
requires-python = ">=3.9"

[project.urls]
Home = "https://github.com/will-henney/teresa-pn-ou5"
