[project]
name = "teresa-pn-ou5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "matplotlib>=3.3",
    "seaborn",
    "astropy",
    "cmasher",
    "pyyaml",
    "jupyter_client",
    "jupyter",
    "jupyterlab",
    "jupytext",
    "mes-longslit",
]

[project.optional-dependencies]
dev = [
    "flit",
    "black",
    "mypy"
]

[tool.uv.sources]
mes-longslit = { workspace = true }

[tool.uv.workspace]
members = ["mes-longslit"]

[project.urls]
Home = "https://github.com/will-henney/teresa-pn-ou5"
