#+OPTIONS: ^:{}
* New slits 2023
- Michael took some new [O III] spectra
- Tere has sent me the files [2023-03-30 Thu]
- But she did not manage to remove the cosmic rays

** Remove cosmic rays
- Python program to remove cosmic rays from the spectra
- Options include ~ccdproc.cosmicray_lacosmic~
- Or astroscrappy, which seems to be the same algorithm


*** Diego's intent to remove cosmic rays
- Diego says it is not working, so I will try it
- I have made the following changes
  - I have changed the path to look in the current folder
  - I have removed the figure parts, since we can just look at the FITS files
#+begin_src sh :dir ../diego-remove-cosmicrays
python remove_cosmicRay.py
#+end_src

#+RESULTS:
    

* Stages in data reduction and analysis
+ I am going to follow similar steps to what I did with the Owl and the Turtle
+ But this time I will try and make a proper re-useable python library, rather than just have snippets of code spread over an org file
+ And I will make jupyter notebooks to demonstrate use of the library
** 00 Preliminary organization
*** Find list of image+slit exposures
+ This is done in [[file:../notebooks/00-00-inspect-orig-files.py][00-00-inspect-orig-files.py]]
  + [[file:../notebooks/00-00-inspect-orig-files.ipynb][00-00-inspect-orig-files.ipynb]]
**** A database of all the image+slit files
| N10035   | Ha        |
| N10042   | Ha        |
| N10047o  | Missing   |
| N20001   | Unfocused |
| N20008   | [O III]   |
| N20011   | Ha        |
| spm0020o | Ha        |
| spm0025o | [O III]   |
| spm0047o | Ha        |
| spm0052o | [O III]   |
| spm0053o | Ha        |
| spm0058o | [O III]   |
| spm0109o | [O III]   |
| spm0210o | Ha        |
| spm0214o | Ha        |
| spm0431o | Ha        |
| spm0439o | Ha        |
| spm0600o | Ha        |

+ I will make a YAML file by hand, even though some of the info could be obtained automatically
+ To start off with, I will key it all by the image name, but I might change that later

#+begin_src yaml :tangle ../data/image-slit-database.yml
  -
    image_id: N10035   
    line_id: Ha        
  -
    image_id: N10042   
    line_id: Ha        
  -
    image_id: N10047o  
    problem: Missing   
  -
    image_id: N20001   
    problem: Unfocused 
  -
    image_id: N20008   
    line_id: O III   
  -
    image_id: N20011   
    line_id: Ha        
  -
    image_id: spm0020o 
    line_id: Ha        
  -
    image_id: spm0025o 
    line_id: O III   
  -
    image_id: spm0047o 
    line_id: Ha        
  -
    image_id: spm0052o 
    line_id: O III   
  -
    image_id: spm0053o 
    line_id: Ha        
  -
    image_id: spm0058o 
    line_id: O III   
  -
    image_id: spm0109o 
    line_id: O III   
  -
    image_id: spm0104o 
    line_id: Ha   
  -
    image_id: spm0210o 
    line_id: Ha        
  -
    image_id: spm0214o 
    line_id: Ha        
  -
    image_id: spm0431o 
    line_id: Ha        
  -
    image_id: spm0439o 
    line_id: Ha        
  -
    image_id: spm0600o 
    line_id: Ha        
#+end_src


*** Set up astrometry.net
1. Find which HEALpix tiles to use
   + This is done in [[file:../notebooks/00-00-inspect-orig-files.py][00-00-inspect-orig-files.py]]
     + [[file:../notebooks/00-00-inspect-orig-files.ipynb][00-00-inspect-orig-files.ipynb]]
2. Download data files from http://data.astrometry.net/5000/
   + I got ~index500[0-4]-14.fits~ and ~index500[5-7]-03.fits~
   + Note that ~astropy_healpix~ did not help much here - it gave a different ID for the tile from what astrometry-net was using
3. Copy data files to [[file:../data/astrometry-net/]]
4. Install ~astrometry-net~
   - Used Homebrew
5. Configure ~astrometry-net~
   - [[file:../data/astrometry-net/astrometry.cfg]]
   - Turn on ~inparallel~
   - Use ~add_path~ to add my data folder (see above)
*** Test of YAML files
**** Make a YAML file for testing
#+begin_src yaml :tangle test.yml
  this: that
  tother:
    - one
    - two
    - three
#+end_src
**** Read in test file as a dict
#+begin_src python :return data :results verbatim
  import yaml

  data = yaml.load(open("test.yml"))
#+end_src

#+RESULTS:
: {'this': 'that', 'tother': ['one', 'two', 'three']}

That seems to work fine

#+begin_src python :return data :results verbatim
  import yaml

  data = yaml.load(open("../data/image-slit-database.yml"))
#+end_src

#+RESULTS:
: [{'image_id': 'N10035', 'line_id': 'Ha'}, {'image_id': 'N10042', 'line_id': 'Ha'}, {'image_id': 'N10047o', 'problem': 'Missing'}, {'image_id': 'N20001', 'problem': 'Unfocused'}, {'image_id': 'N20008', 'line_id': 'O III'}, {'image_id': 'N20011', 'line_id': 'Ha'}, {'image_id': 'spm0020o', 'line_id': 'Ha'}, {'image_id': 'spm0025o', 'line_id': 'O III'}, {'image_id': 'spm0047o', 'line_id': 'Ha'}, {'image_id': 'spm0052o', 'line_id': 'O III'}, {'image_id': 'spm0053o', 'line_id': 'Ha'}, {'image_id': 'spm0058o', 'line_id': 'O III'}, {'image_id': 'spm0109o', 'line_id': 'O III'}, {'image_id': 'spm0210o', 'line_id': 'Ha'}, {'image_id': 'spm0214o', 'line_id': 'Ha'}, {'image_id': 'spm0431o', 'line_id': 'Ha'}, {'image_id': 'spm0439o', 'line_id': 'Ha'}, {'image_id': 'spm0600o', 'line_id': 'Ha'}]

**** Load into a dataframe and astropy Table

Astropy table deals well with missing values

#+begin_src python :return data :results verbatim
  import yaml
  from astropy.table import Table

  data = yaml.load(open("../data/image-slit-database.yml"))
  data = Table(data)
#+end_src

#+RESULTS:
#+begin_example
image_id line_id  problem 
-------- ------- ---------
  N10035      Ha        --
  N10042      Ha        --
 N10047o      --   Missing
  N20001      -- Unfocused
  N20008   O III        --
  N20011      Ha        --
spm0020o      Ha        --
spm0025o   O III        --
spm0047o      Ha        --
spm0052o   O III        --
spm0053o      Ha        --
spm0058o   O III        --
spm0109o   O III        --
spm0210o      Ha        --
spm0214o      Ha        --
spm0431o      Ha        --
spm0439o      Ha        --
spm0600o      Ha        --
#+end_example

And so does pandas:

#+begin_src python :return data :results verbatim
  import yaml
  from pandas import DataFrame

  data = yaml.load(open("../data/image-slit-database.yml"))
  data = DataFrame(data)
#+end_src

#+RESULTS:
#+begin_example
    image_id line_id    problem
0     N10035      Ha        NaN
1     N10042      Ha        NaN
2    N10047o     NaN    Missing
3     N20001     NaN  Unfocused
4     N20008   O III        NaN
5     N20011      Ha        NaN
6   spm0020o      Ha        NaN
7   spm0025o   O III        NaN
8   spm0047o      Ha        NaN
9   spm0052o   O III        NaN
10  spm0053o      Ha        NaN
11  spm0058o   O III        NaN
12  spm0109o   O III        NaN
13  spm0210o      Ha        NaN
14  spm0214o      Ha        NaN
15  spm0431o      Ha        NaN
16  spm0439o      Ha        NaN
17  spm0600o      Ha        NaN
#+end_example


*** Databases of all the spectrum slits
**** [O III] slits
#+begin_src yaml :tangle ../data/slits-o3.yml
  -
    slit_id: N10039
    orig_file: crN10039_bx-oiii.fits
    image_id: N10035
    line_id: O III
    slit_width: 70
    comment: >-
      Just E of center. 
      Highest resolution for the inner shell.
      Image is Ha, not O III. 
  -
    slit_id: N10045
    orig_file: crN10045_bx-oiii.fits
    image_id: N10042
    line_id: O III
    slit_width: 70
    comment: >-
      Grazes E limb.
      Shows part of outer lobe.
      Image is Ha, not O III.
  -
    slit_id: N20006
    orig_file: crN20006_bx-oiii.fits
    image_id: N20008
    line_id: O III
    slit_width: 70
    comment: >-
      Crosses E limb. 
  -
    slit_id: spm0023o
    orig_file: crspm0023o_bx-oiii.fits
    image_id: spm0025o
    line_id: O III
    slit_width: 150
    comment: >-
      Grazes E limb. 
  -
    slit_id: spm0050o
    orig_file: crspm0050o_bx.fits
    image_id: spm0052o
    line_id: O III
    slit_width: 150
    comment: >-
      E of center.
      Shows outer lobes well.
      Shows central blue wing.
  -
    slit_id: spm0056o
    orig_file: crspm0056o_bx.fits
    image_id: spm0058o
    line_id: O III
    slit_width: 150
    comment: >-
      Just W of center.
      Shows outer lobes well.
      Shows central blue wing.
      Shows weak continuum from unrelated star. 
  -
    slit_id: spm0107o
    orig_file: crspm0107o_bx.fits
    image_id: spm0109o
    line_id: O III
    slit_width: 150
    comment: >-
      W of center.
      Shows outer lobes well.
      Shows central blue wing.

#+end_src

+ Some thoughts:
  - We could co-add the last 3 [O III] slits: spm0050o, spm0056o, spm0107o
    - They look very similar in nearly all respects, and it would improve s/n for the fainter features
  - We have no [O III] slits of the W limb, which is a shame


Check that the file loads OK.

#+begin_src python :return data :results verbatim
  import yaml
  from pandas import DataFrame

  data = yaml.load(open("../data/slits-o3.yml"))
  data = DataFrame(data)
#+end_src

#+RESULTS:
#+begin_example
    slit_id  ...                                            comment
0    N10039  ...  Just E of center.  Highest resolution for the ...
1    N10045  ...            Grazes E limb.  Image is Ha, not O III.
2    N20006  ...                                   Crosses E limb. 
3  spm0023o  ...                                    Grazes E limb. 
4  spm0050o  ...  E of center. Shows outer lobes well. Shows cen...
5  spm0056o  ...  Exact center. Shows outer lobes well. Shows ce...
6  spm0107o  ...  W of center. Shows outer lobes well. Shows cen...

[7 rows x 6 columns]
#+end_example

Looks good. 

**** Ha slits
#+begin_src yaml :tangle ../data/slits-ha.yml
  -
    slit_id: N10036
    orig_file: crN10036_bx.fits
    image_id: N10035
    line_id: Ha
    slit_width: 70
    comment: >-
      Just E of center.
  -
    slit_id: N10043
    orig_file: crN10043_bx.fits
    image_id: N10042
    line_id: Ha
    slit_width: 70
    comment: >-
      Grazes E limb.
  -
    slit_id: N20004
    orig_file: crN20004_bx.fits
    image_id: N20008
    line_id: Ha
    slit_width: 70
    comment: >-
      Crosses E limb.
      Image is O III, not Ha.
  -
    slit_id: N20012
    orig_file: crN20012_bx.fits
    image_id: N20011
    line_id: Ha
    slit_width: 70
    comment: >-
      W of center.
  -
    slit_id: spm0021o
    orig_file: crspm0021o_bx.fits
    image_id: spm0020o
    line_id: Ha
    slit_width: 150
    comment: >-
      Grazes E limb.
  -
    slit_id: spm0048o
    orig_file: crspm0048o_bx.fits
    image_id: spm0047o
    line_id: Ha
    slit_width: 150
    comment: >-
      Just E of center.
  -
    slit_id: spm0054o
    orig_file: crspm0054o_bx.fits
    image_id: spm0053o
    line_id: Ha
    slit_width: 150
    comment: >-
      Just W of center.
      Crosses unrelated star.
  -
    slit_id: spm0105o
    orig_file: crspm0105o_bx.fits
    image_id: spm0104o
    line_id: Ha
    slit_width: 150
    comment: >-
      W of center.
  -
    slit_id: spm0211o
    orig_file: crspm0211o_b1t.fits
    image_id: spm0210o
    line_id: Ha
    slit_width: 150
    comment: >-
      Just W of center.
  -
    slit_id: spm0215o
    orig_file: crspm0215o_b1t.fits
    image_id: spm0214o
    line_id: Ha
    slit_width: 150
    comment: >-
      Crosses W limb.
  -
    slit_id: spm0432o
    orig_file: crspm0432o_b1t.fits
    image_id: spm0431o
    line_id: Ha
    slit_width: 150
    comment: >-
      E of center.
  -
    slit_id: spm0440o
    orig_file: crspm0440o_b1t.fits
    image_id: spm0439o
    line_id: Ha
    slit_width: 150
    comment: >-
      Horizontal slit.
  -
    slit_id: spm0601o
    orig_file: crspm0601o_b1t.fits
    image_id: spm0600o
    line_id: Ha
    slit_width: 150
    comment: >-
      Crosses W limb.


#+end_src

#+begin_src python :return data :results verbatim
  import yaml
  from pandas import DataFrame

  data = yaml.load(open("../data/slits-ha.yml"))
  data = DataFrame(data)
#+end_src

#+RESULTS:
#+begin_example
     slit_id            orig_file  ...            trim shift_range
0     N10036     crN10036_bx.fits  ...             NaN         NaN
1     N10043     crN10043_bx.fits  ...             NaN         NaN
2     N20004     crN20004_bx.fits  ...             NaN         NaN
3     N20012     crN20012_bx.fits  ...  [0, 0, 0, -50]   [50, 110]
4   spm0021o   crspm0021o_bx.fits  ...             NaN         NaN
5   spm0048o   crspm0048o_bx.fits  ...             NaN         NaN
6   spm0054o   crspm0054o_bx.fits  ...             NaN         NaN
7   spm0105o   crspm0105o_bx.fits  ...             NaN         NaN
8   spm0211o  crspm0211o_b1t.fits  ...             NaN         NaN
9   spm0215o  crspm0215o_b1t.fits  ...             NaN         NaN
10  spm0432o  crspm0432o_b1t.fits  ...             NaN         NaN
11  spm0440o  crspm0440o_b1t.fits  ...             NaN         NaN
12  spm0601o  crspm0601o_b1t.fits  ...             NaN         NaN

[13 rows x 10 columns]
#+end_example

** [2/2] 01 Astrometry and median combination of images+slit

*** DONE TASK 01-00 Run ~astrometry-net~ on all the images
CLOSED: [2021-11-05 Fri 19:45]
+ The only tricky parts here were
  1. Finding the correct HEALpix tile (see above)
  2. Putting sensible limits on the pixel scale
+ Once those were resolved then solutions are found very rapidly for all the images.
+ Run these in the terminal
  + I divide the images in two groups since the pixel scale is different
+ The ones starting ~crN~ have 2x2 binning
  #+begin_src sh :dir ../data :results verbatim :eval no
    for F in $(grep crN image-list.dat); do
        solve-field --config astrometry-net/astrometry.cfg \
                --ra 318.58 --dec 43.69 --radius 1.0\
                --scale-units arcsecperpix --scale-low 0.3 --scale-high 0.4\
                --depth 50 --dir wcs --new-fits '%s-wcs.fits'\
                --no-tweak --overwrite originals/$F.fits 
    done
  #+end_src
+ The ones starting ~crspm~ have 3x3 binning
  #+begin_src sh :dir ../data :results verbatim :eval no
    for F in $(grep crspm image-list.dat); do
        solve-field --config astrometry-net/astrometry.cfg \
                --ra 318.58 --dec 43.69 --radius 1.0\
                --scale-units arcsecperpix --scale-low 0.5 --scale-high 0.6\
                --depth 50 --dir wcs --new-fits '%s-wcs.fits'\
                --no-tweak --overwrite originals/$F.fits 
    done
  #+end_src
+ The one I forgot
  #+begin_src sh :dir ../data :results verbatim :eval no
    F=crspm0104o_b
    solve-field --config astrometry-net/astrometry.cfg \
            --ra 318.58 --dec 43.69 --radius 1.0\
            --scale-units arcsecperpix --scale-low 0.5 --scale-high 0.6\
            --depth 50 --dir wcs --new-fits '%s-wcs.fits'\
            --no-tweak --overwrite originals/$F.fits 
  #+end_src


*** DONE TASK 01-01 Generating the median images
CLOSED: [2021-11-05 Fri 19:45]
+ This is done in the notebook
  + [[file:../notebooks/01-00-image-astrometry.py]]
** [3/3] 02 Photometry and WCS info for slit spectra
+ We will generally follow the Turtle plan
+ But another thing we could do is to use the BG component in H alpha
*** DONE TASK 02-00 Port the routines from ~turtle_utils.py~
CLOSED: [2021-11-10 Wed 19:23]
+ These need to be generalised a bit and put in [[file:../src/mes_longslit/]]
+ They are in [[file:../src/mes_longslit/slit_utils.py]]
*** DONE TASK 02-01 Reference profiles from median image and compare with slit profiles
CLOSED: [2021-11-10 Wed 19:24]
+ This is done in [[file:../notebooks/02-01-test-normalize.py]] for Ha
+ And in [[file:../notebooks/02-02-o3-normalize.py]] for [O III]
+ They use the routine ~pv_extract()~ from the library

*** DONE [#B] TASK 02-03 Write out extracted PV spectra with celestial coordinates
CLOSED: [2021-11-10 Wed 19:27]
+ This is done with the same notebooks as above
+ The files are in [[file:../data/pvextract/]]
+ The have two different WCS systems
  + Default is just wavelength, offset
  + ~A~ is a fancy one
    + with 3 WCS axes mapping on to 2 image axes
    + wavelength, RA, and Dec


** DONE [#A] 03 Isovelocity images
CLOSED: [2022-03-02 Wed 07:22]
+ This is done in 03-01-test-vmap
  + Notebook [[file:../notebooks/03-01-test-vmap.ipynb]]
  + Pure python version: [[file:../notebooks/03-01-test-vmap.py]]
** DONE 04 Combine axial slits and make some plots
CLOSED: [2022-04-19 Tue 22:05]
+ To improve the signal-to-noise, we can add together the slits that are not too far from the nebular axis
+ This is done in 04-01-coadd-slits
  + [[file:../notebooks/04-01-coadd-slits.ipynb]]
  + [[file:../notebooks/04-01-coadd-slits.py]]
+ The results are in [[file:../data/pv-common/]]
+ We also made some 1D spectra plots
** TODO Comparison of my slit positions with the paper
:LOGBOOK:
- State "TODO"       from              [2025-08-01 Fri 13:18] \\
  I am not sure that I believe all the slit positions that Tere has put in the paper
:END:
*** Table of spectra from 00-00-inspect-orig-files
- This is from the fits headers of all the files
- I am adding offset positions from 04-01-coadd-slits
**** Organized by date
| idx | File               |   DATE-OBS | FILTER   |          RA |          DEC | PA              | OFFSET | Tere |
|-----+--------------------+------------+----------+-------------+--------------+-----------------+--------+------|
|   1 | crN10036_bx        | 2017-08-29 | Ha 90A   |  21:15:04.3 |   43:46:40.0 | 8.63 , -351.37  |   2.32 | c    |
|   2 | crN10039_bx-oiii   | 2017-08-29 | OIII 60A |  21:15:02.8 |   43:46:48.0 | 8.63 , -351.37  |  2.324 | c    |
|   4 | crN10043_bx        | 2017-08-29 | Ha 90A   |  21:15:02.3 |   43:46:58.0 | 8.63 , -351.37  |   4.72 | b    |
|   5 | crN10045_bx-oiii   | 2017-08-29 | OIII 60A |  21:15:02.3 |    43:47:7.0 | 8.63 , -351.37  |   5.07 | b    |
|   8 | crN20004_bx        | 2017-08-30 | Ha 90A   |  21:15:03.8 |   43:45:27.0 | 360.00 , -0.00  |   4.53 | b    |
|   9 | crN20006_bx-oiii   | 2017-08-30 | OIII 60A |  21:15:03.9 |   43:45:26.0 | 360.00 , -0.00  |   4.53 | b    |
|  12 | crN20012_bx        | 2017-08-30 | Ha 90A   |  21:15:03.3 |   43:45:22.0 | 360.00 , -0.00  |  -0.38 | d    |
|  14 | crspm0021o_bx      | 2018-05-02 | Ha 90A   |  21:15:04.0 |    43:49:3.0 | 359.90 , -0.10  |   8.20 | a    |
|  15 | crspm0023o_bx-oiii | 2018-05-02 | OIII 60A |  21:15:05.1 |   43:48:57.0 | 359.90 , -0.10  |   8.81 | a    |
|  18 | crspm0048o_bx      | 2018-05-03 | Ha 90A   |  21:15:04.9 |   43:49:46.0 | 359.98 , -0.02  |   1.69 | c    |
|  19 | crspm0050o_bx      | 2018-05-03 | OIII 60A |  21:15:06.1 |   43:49:40.0 | 359.98 , -0.02  |   3.01 | c    |
|  22 | crspm0054o_bx      | 2018-05-03 | Ha 90A   |  21:15:07.6 |   43:49:29.0 | 359.98 , -0.02  |  -0.85 | d    |
|  23 | crspm0056o_bx      | 2018-05-03 | OIII 60A |  21:15:08.6 |   43:49:25.0 | 359.98 , -0.02  |  -0.19 | d    |
|  26 | crspm0105o_bx      | 2018-05-04 | Ha 90A   |  21:14:55.4 |   43:47:27.0 | 359.98 , -0.02  |  -3.24 | e    |
|  27 | crspm0107o_bx      | 2018-05-04 | OIII 60A |  21:14:56.6 |   43:47:22.0 | 359.98 , -0.02  |  -2.82 | e    |
|  30 | crspm0211o_b1t     | 2019-09-15 | Ha 90A   | 21:14:55.47 | +43:47:23.41 | 0.30 , -359.70  |  -0.38 | d    |
|  32 | crspm0215o_b1t     | 2019-09-15 | Ha 90A   | 21:14:55.00 | +43:47:34.36 | 0.30 , -359.70  |  -5.22 | f    |
|  34 | crspm0432o_b1t     | 2019-09-17 | Ha 90A   | 21:14:57.42 | +43:46:46.66 | 0.26 , -359.74  |   3.22 | b    |
|  36 | crspm0440o_b1t     | 2019-09-17 | Ha 90A   | 21:14:57.50 | +43:46:30.76 | 84.35 , -275.65 |  0.317 | g    |
|  38 | crspm0601o_b1t     | 2019-09-18 | Ha 90A   | 21:15:03.60 | +43:46:43.22 | 0.26 , -359.74  |  -6.29 | f    |
|     |                    |            |          |             |              |                 |        |      |
**** Organized by position, slit width, line
Vertical Ha 150

| idx | File           |   DATE-OBS | FILTER |          RA |          DEC | PA             | OFFSET | Tere |
|-----+----------------+------------+--------+-------------+--------------+----------------+--------+------|
|  14 | crspm0021o_bx  | 2018-05-02 | Ha 90A |  21:15:04.0 |    43:49:3.0 | 359.90 , -0.10 |   8.20 | a    |
|  34 | crspm0432o_b1t | 2019-09-17 | Ha 90A | 21:14:57.42 | +43:46:46.66 | 0.26 , -359.74 |   3.22 | b    |
|  18 | crspm0048o_bx  | 2018-05-03 | Ha 90A |  21:15:04.9 |   43:49:46.0 | 359.98 , -0.02 |   1.69 | c    |
|  30 | crspm0211o_b1t | 2019-09-15 | Ha 90A | 21:14:55.47 | +43:47:23.41 | 0.30 , -359.70 |  -0.38 | d    |
|  22 | crspm0054o_bx  | 2018-05-03 | Ha 90A |  21:15:07.6 |   43:49:29.0 | 359.98 , -0.02 |  -0.85 | d    |
|  26 | crspm0105o_bx  | 2018-05-04 | Ha 90A |  21:14:55.4 |   43:47:27.0 | 359.98 , -0.02 |  -3.24 | e    |
|  32 | crspm0215o_b1t | 2019-09-15 | Ha 90A | 21:14:55.00 | +43:47:34.36 | 0.30 , -359.70 |  -5.22 | f    |
|  38 | crspm0601o_b1t | 2019-09-18 | Ha 90A | 21:15:03.60 | +43:46:43.22 | 0.26 , -359.74 |  -6.29 | f    |

Vertical Ha 70

| idx | File        |   DATE-OBS | FILTER |         RA |        DEC | PA             | OFFSET | Tere |
|-----+-------------+------------+--------+------------+------------+----------------+--------+------|
|   4 | crN10043_bx | 2017-08-29 | Ha 90A | 21:15:02.3 | 43:46:58.0 | 8.63 , -351.37 |   4.72 | b    |
|   8 | crN20004_bx | 2017-08-30 | Ha 90A | 21:15:03.8 | 43:45:27.0 | 360.00 , -0.00 |   4.53 | b    |
|   1 | crN10036_bx | 2017-08-29 | Ha 90A | 21:15:04.3 | 43:46:40.0 | 8.63 , -351.37 |   2.32 | c    |
|  12 | crN20012_bx | 2017-08-30 | Ha 90A | 21:15:03.3 | 43:45:22.0 | 360.00 , -0.00 |  -0.38 | d    |


Vertical [O III] 150

| idx | File               |   DATE-OBS | FILTER   |         RA |        DEC | PA             | OFFSET | Tere |
|-----+--------------------+------------+----------+------------+------------+----------------+--------+------|
|  15 | crspm0023o_bx-oiii | 2018-05-02 | OIII 60A | 21:15:05.1 | 43:48:57.0 | 359.90 , -0.10 |   8.81 | a    |
|  19 | crspm0050o_bx      | 2018-05-03 | OIII 60A | 21:15:06.1 | 43:49:40.0 | 359.98 , -0.02 |   3.01 | c    |
|  23 | crspm0056o_bx      | 2018-05-03 | OIII 60A | 21:15:08.6 | 43:49:25.0 | 359.98 , -0.02 |  -0.19 | d    |
|  27 | crspm0107o_bx      | 2018-05-04 | OIII 60A | 21:14:56.6 | 43:47:22.0 | 359.98 , -0.02 |  -2.82 | e    |

Vertical [O III] 70
| idx | File             |   DATE-OBS | FILTER   |         RA |        DEC | PA             | OFFSET | Tere |
|-----+------------------+------------+----------+------------+------------+----------------+--------+------|
|   5 | crN10045_bx-oiii | 2017-08-29 | OIII 60A | 21:15:02.3 |  43:47:7.0 | 8.63 , -351.37 |   5.07 | b    |
|   9 | crN20006_bx-oiii | 2017-08-30 | OIII 60A | 21:15:03.9 | 43:45:26.0 | 360.00 , -0.00 |   4.53 | b    |
|   2 | crN10039_bx-oiii | 2017-08-29 | OIII 60A | 21:15:02.8 | 43:46:48.0 | 8.63 , -351.37 |  2.324 | c    |


Horizontal
| idx | File           |   DATE-OBS | FILTER |          RA |          DEC | PA              | OFFSET | Tere |
|-----+----------------+------------+--------+-------------+--------------+-----------------+--------+------|
|  36 | crspm0440o_b1t | 2019-09-17 | Ha 90A | 21:14:57.50 | +43:46:30.76 | 84.35 , -275.65 |  0.317 | g    |


* Initial messages from Teresa
** 2021-06-21
: Al ver los espectros, se ven con mucho ruido, esto es porque eliminé
: el background, creo que mejor te envio los originales para que también
: tengan el mismo tamaño, el último corte lo hice antes de cambiar la
: versión de la mac, de hecho haré como con la tortuga, te envio todo el
: material ya que no he tomado en cuenta algunas posiciones, tal vez
: sean de utilidad para la parte central.

#+begin_example
  ,*****************
  28 de Agosto 2017
  ,*****************

  N1035 I+S  Halpha
  N1036 espectro Ha
  N1039 espelctro [OIII]

  N1042 I+S
  N1043 espectro Ha
  N1045 espectro [OIII]
  N1047 slit+image

  N2001 I+S desenfocada
  N2004 espectro ha
  N2006 espectro [OIII]
  N2008 I+S confiar en esta posicion

  POSICION D
  N2011 I+S
  N2012 espec ha


  MAYO 1 2018

  crspm0021o_bx.fits Ha
  crspm0023o_bx oiii


  MAYO 2 2018

  crspm047 i+s
  crspm048 espec
  crspm050 spec
  crspm052 s+i

  crspm053 i+s
  crspm054 spec
  crspm056 spec
  crspm058 S+i

  spm104 I+S
  spm105 esp
  spm106 lamp
  spm107 spe
  spm108 arc
  spm109 s+i

  14/09/2019

  Ha

  spm0210 I+S
  spm0211 spec

  spm0214 I+S
  spm0215 spec

  spm0431 I+S
  spm0432 spec


  spm0439 I+S
  spm0440 spec


  spm0600 I+S
  spm0601 spec
#+end_example

